# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_title',
        ),
    ]
