# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_song_song_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_title',
            field=models.CharField(default='default', max_length=250),
            preserve_default=False,
        ),
    ]
